COMPONENT=BaseStationC
CFLAGS += -DCC2420_NO_ACKNOWLEDGEMENTS
CFLAGS += -DCC2420_NO_ADDRESS_RECOGNITION
CFLAGS += -DTASKLET_IS_TASK

CC2420_CHANNEL=25
# CFLAGS=-DCC2420_DEF_RFPOWER=31 
#make tmote
#rssi.h file path
INCLUDES= -I..
CFLAGS += $(INCLUDES)

#java build
BUILD_EXTRA_DEPS += TestSerial.class
CLEAN_EXTRA = *.class TestSerialMsg.java

CFLAGS += -I$(TOSDIR)/lib/T2Hack

TestSerial.class: $(wildcard *.java) TestSerialMsg.java
	javac *.java #-target 1.4 -source 1.4 *.java

TestSerialMsg.java:
	mig java -target=null $(CFLAGS) -java-classname=TestSerialMsg RSSI.h TrackerMsg -o $@


include $(MAKERULES)
